/*
-- Query: SELECT * FROM m2.stock
LIMIT 0, 1000

-- Date: 2017-03-25 16:10
*/
INSERT INTO `stock` (`STOCK_ID`,`STOCK_CODE`,`STOCK_NAME`) VALUES (2,'20','Bob');
INSERT INTO `stock` (`STOCK_ID`,`STOCK_CODE`,`STOCK_NAME`) VALUES (3,'25','Charlie');
INSERT INTO `stock` (`STOCK_ID`,`STOCK_CODE`,`STOCK_NAME`) VALUES (4,'99','Pera');
INSERT INTO `stock` (`STOCK_ID`,`STOCK_CODE`,`STOCK_NAME`) VALUES (5,'66','Jelka');
INSERT INTO `stock` (`STOCK_ID`,`STOCK_CODE`,`STOCK_NAME`) VALUES (6,'199','Pera1');
INSERT INTO `stock` (`STOCK_ID`,`STOCK_CODE`,`STOCK_NAME`) VALUES (7,'166','Jelka1');
